### ISSUE TITLE
How to prevent page break after every section?

### ISSUE THREAD

**Issue by jmichaelegana** [quantixed/manuscript-templates#2]
If a section is created, it forces a new page to be created. I have tried methods suggested in this thread: https://groups.google.com/g/comp.text.tex/c/ciatXgOObpM e.g. unbreakable and \filbreak but to no avail.

Thanks in advance!

**Comment by quantixed** [comment]
Hi @jmichaelegana,
In bioRxiv mode (`twocolumn`), a new section doesn't force a new page to be created. In `submit` mode, `section*{}` does indeed force a new page.

If you comment lines 277-280 in `bioRxiv.cls`:
```
% \if@submit
%   \let\oldsection\section
%   \renewcommand\section{\clearpage\oldsection}
% \fi
```
It should give you the behaviour you want. Let me know if that fixes your problem.

**Comment by jmichaelegana** [comment]
This works. Thank you very much.
